language: node_js
node_js:
  - 10.15.3
os:
  - osx
notifications:
  email: false
install:
  - npm install
jobs:
  include:
    - stage: "Lint, Test and Build"
    - script: npm run lint && npm run test && npm run generate
    - stage: "Staging"
    - script: npm run generate
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: $FIREBASE_TOKEN
        project: "nwhacks-2019-dev"
        on:
          branch: dev
    - stage: Deploy
      script: npm run generate:prod && echo "cms.nwplus.io" >> dist/CNAME
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: dist
        on:
          branch: master
stages:
  - "Lint, Test and Build"
  - name: Deploy
    if: branch = master